version: "2.1"

services:
  activemq:
    image: webcenter/activemq
    ports:
      # ui
      - "8161:8161"
      # jms
      - "61616:61616"
    environment:
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048